global using System.Collections.ObjectModel;
global using CommunityToolkit.Maui;
global using CommunityToolkit.Maui.Core;
global using CommunityToolkit.Maui.Markup;
global using CommunityToolkit.Mvvm.ComponentModel;
global using Dome.Shared.Constants;
global using Dome.Shared.Helper;
global using static Dome.Shared.Local.Enums;
global using Dome.Shared.Services.Interfaces;
global using Dome.Shared.Services.Interfaces.Authentication;
global using Dome.Shared.Synced.Player;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Maui.Controls;
global using MongoDB.Bson;
global using Mopups.Pages;
global using Ory.Client.Api;
global using Ory.Client.Client;
global using Ory.Client.Model;
global using Realms;
global using Twilio;
global using Twilio.Rest.Verify.V2.Service;
global using Stream = System.IO.Stream;
global using Task = System.Threading.Tasks.Task;
